import sys
import json 
import random 
import os 
import argparse
import random
import time
from config import keys, Qwen_Max

random.seed(int(time.time()))
os.environ["QWEN_API_KEY"] = random.choice(keys)
sys.path.append("./")

def qwenmax_eval_instruction_semantic(question, response, instruct, qwenmax):
    prompt = f'''
You are an objective instruction compliance assessment assistant. I will provide the following three components:

Instruction: A user instruction involving explicit requirements.
Response: The response generated by a model for this instruction.
Judgment Criteria: The criteria used to judge whether the model correctly follows the instruction.

Returns whether the model correctly follows the user's instruction. Note that the assessment is based solely on the judgment criteria and is not influenced by factual errors, response quality, or other factors.

Output Format
Correct/Incorrect [Simple Explanation]
Example: Correct. The model correctly repeated the user's words according to the instruction.

Question: {question}
Model Response: {response}
Judgment Criteria: {instruct}
  ''' 

    for i in range(10):
        messages = [
            {
                "role": "user",
                "content": prompt
            }
        ]
        print(messages)
        text = qwenmax(messages)["text"]
        
        if text.startswith("Correct"):
            return 1, text
        elif text.startswith("Incorrect"):
            return 0, text
        score = 0
    return score, text


def qwenmax_eval_json(input_json, output_json):

    instances = []
    finished_len = 0
    correct_num = 0
    set_to_id = {
        "Plain repeat": 0,
        "With emotion": 1,
        "With speed": 2,
        "With speed & emotion": 3,
        "Num": 4,
        "Constrain": 5,
        "Keywords": 6,
        "Progressive": 7,
        "Conditional": 8,
        "Topic change": 9,
        "Spoken format": 10,
        "Speaker tune": 11,
        "Speaking style": 12,
        "Instruction": 13,
        "Situation": 14,
        "Format": 15
    }

    instructions = [
    "The model's response must include the complete content that the user requests to be repeated. Minor word errors and additional explanations are allowed.",
    "The model's response must include the complete content that the user requests to be repeated. Minor word errors and additional explanations are allowed.",
    "The model's response must include the complete content that the user requests to be repeated. Minor word errors and additional explanations are allowed.",
    "The model's response must include the complete content that the user requests to be repeated. Minor word errors and additional explanations are allowed.",
    "The model must strictly list the exact number of items specified by the user. Providing more or fewer items is considered non-compliant with the instruction.",
    "The model must include the specified content at the designated position and ensure the required terms appear the mandated number of times. Failure to meet any of these requirements is considered non-compliant with the instruction.",
    "The model must include all specified keywords and must not include any excluded keywords. Any deviation is considered non-compliant with the instruction.",
    "The model must answer each question strictly in the order presented. Answering in the wrong sequence or omitting any question is considered non-compliant with the instruction.",
    "The model must select the appropriate follow-up question based on the judgment from the preliminary question. Answering the wrong follow-up question or answering both follow-ups simultaneously is considered non-compliant; however, if the preliminary judgment itself is incorrect but leads to a logically consistent choice of follow-up, it is still considered compliant.",
    "The model must follow only the user’s final corrected instruction. Responding to earlier instructions or addressing both pre- and post-correction instructions is considered non-compliant.",
    "The model must respond using purely colloquial language. Inclusion of LaTeX code, formulas, or other structured text is considered non-compliant with the instruction.",
    "The model must use an appropriate and reasonable tone and language style tailored to the specified audience or its own assigned identity. Inappropriate, untimely, or overly direct language is considered non-compliant with the instruction.",
    "The model must strictly mimic the specified character’s style in its reply. Deviating from the required style or using a flat, plain narrative is considered non-compliant with the instruction.",
    "The model must strictly adhere to the user-specified wording, structure, and content sequence. Any deviation or omission is considered non-compliant with the instruction.",
    "The model must fully consider and address all specific circumstances described by the user. Omission or clear contradiction is considered non-compliant with the instruction.",
    "The model must strictly follow the format specified by the user. Any format deviation is considered non-compliant with the instruction."
    ]

    if os.path.exists(output_json):
        with open(output_json, "r") as f:
            finished = json.load(f)
        for item in finished:
            instances.append(item)
            correct_num += item["Correct"]
        finished_len = int(instances[-1]["Qid"].split('-')[-1]) + 1
        finished_len = len(finished)
        
    with open("../json/instruction.json", "r") as f:
        ref = json.load(f)
    with open(input_json, "r") as f:
        data = json.load(f)
  
    qwenmax = Qwen_Max(model_name="qwen-max-2025-01-25")
    for instance in data[finished_len:]:
        index = int(instance['Qid'].split('-')[1])
        if ref[index].get("Sub-category", None) is not None:
              set_id = set_to_id[ref[index]["Sub-category"]]
        else:
              set_id = set_to_id[ref[index]["Category"]]
        instruct = instructions[set_id]
        question = ref[index]['Question']
        response = instance['Response']

        correct, explain = qwenmax_eval_instruction_semantic(question, response, instruct, qwenmax)
        correct_num += correct
        instances.append({
          'Qid': instance['Qid'],
          'Question': question,
          'Response': response,
          'Correct': correct,
          'Explain': explain
        })

        with open(output_json, 'w+', encoding = 'utf-8') as outf:
          json.dump(instances, outf, ensure_ascii=False, indent = 4)
      
    print(f"Semantic Accuracy: {correct_num/len(instances)*100}%")

        
if __name__ == "__main__": 
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_json", type=str)
    parser.add_argument("--output_json", type=str)
    args = parser.parse_args()

    qwenmax_eval_json(args.input_json, args.output_json)

