import sys
import json 
import random 
import os 
import re
import argparse
import random
import time
from config import keys, Qwen_Max


random.seed(int(time.time()))
os.environ["QWEN_API_KEY"] = random.choice(keys)
sys.path.append("./")


def tn_en(text):
    cleaned = re.sub(r'[^a-zA-Z\s.,?!]', '', text)
    return cleaned

def qwenmax_infer_instance(question, pred, reference, history, qwenmax):
    context = ""
    for turn in history:
        if turn['from'] == 'user':
            context = context + f"User: {turn['value']}\n"
        elif turn['from'] == 'assistant':
            context = context + f"Model: {turn['value']}\n"
    prompt = f'''
You are an objective question-answering evaluation assistant. Next, I will provide the following four components:
History: The history of the user's dialogue with the model.
Question: A question from the user after their historical dialogue.
Answer: The correct answer to the question.
Response: The response generated by the model for the question.

Please analyze and evaluate according to the following requirements:
Determine whether the result contained in the "Response" is consistent with the "Answer". 

Output Format: Correct/Wrong [Simple Explanation]
Example: Correct. The model provided a clear answer, and it is consistent with the correct answer.

History: {context}
Question: {question}
Answer: {reference}
Response: {pred} 
  '''
    for i in range(10):
        messages = [
            {
                "role": "user",
                "content": prompt
            }
        ]
        text = tn_en(qwenmax(messages)["text"])
        if text.startswith('Correct'):
            return 1, text
        elif text.startswith('Wrong'):
            return 0, text
        score = -1
    return score, text


def qwenmax_eval_json(input_json, output_json):
    eval_data = []
    finished_len = 0
    correct_num = 0

    if os.path.exists(output_json):
        with open(output_json, "r") as f:
            finished = json.load(f)
        for item in finished:
            eval_data.append(item)
        finished_len = len(finished)
        
    with open("../json/multi_round.json", "r") as f:
        ref = json.load(f)
    with open(input_json, "r") as f:
        data = json.load(f)
    

    qwenmax = Qwen_Max(model_name="qwen-max-2025-01-25")
    for instance in data[finished_len:]:
        response = instance["Response"]
        index = int(instance["Qid"].split('-')[-1])
        question = ref[index]["Question"]
        reference = ref[index]["Answer"]
        context = ref[index]["Context"]

        correct, explain = qwenmax_infer_instance(question, response, reference, context, qwenmax)
        eval_data.append({
            "Qid": instance["Qid"],
            "Question": question,
            "Reference": reference,
            "Response": response,
            "Correct": correct,
            "Explain": explain
        })
        with open(output_json, 'w+', encoding='utf-8') as f:
            json.dump(eval_data, f, ensure_ascii=False, indent=4)
            
    for instance in eval_data:
        correct_num += instance['Correct'] 
    print(f"Average Accuracy: {correct_num/(len(eval_data))*100}%")


if __name__ == "__main__": 
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_json", type=str)
    parser.add_argument("--output_json", type=str)

    args = parser.parse_args()
    qwenmax_eval_json(args.input_json, args.output_json)
