import json
import sys
import random 
import os 
import re
import argparse
import random
import time
from config import keys, Qwen_Max

random.seed(int(time.time()))
os.environ["QWEN_API_KEY"] = random.choice(keys)
sys.path.append("./")

def tn_en(text):
    cleaned = re.sub(r'[^a-zA-Z0-9\s.,?!]', '', text)
    return cleaned

def qwenmax_eval_with_ans(question, pred, reference, qwenmax):
    prompt = f'''
You are an objective question-answering evaluation assistant. Next, I will provide the following three components:

Question: A question involving simple logical reasoning or mathematical operations.
Answer: The correct answer to the question.
Response: The response generated by the model for the question.

Please analyze and evaluate according to the following requirements:
Determine whether the result contained in the "Response" is consistent with the "Answer". 

Output Format: Correct/Wrong [Simple Explanation]
Example: Correct. The model provides a clear calculation result, which is consistent with the correct answer.

Question: {question}
Answer: {reference}
Response: {pred}
  ***
  '''
    for i in range(10):
        messages = [
            {
                "role": "user",
                "content": prompt
            }
        ]
        print(messages)
        text = tn_en(qwenmax(messages)["text"])
        if text.startswith('Correct'):
            return 1, text
        elif text.startswith('Wrong'):
            return 0, text
        score = -1
    return score, text


def qwenmax_eval_open_domain(question, pred, reference, qwenmax):
    prompt = f'''
You are an objective question-answering evaluation assistant. Next, I will provide the following three components:

Question: A question involving simple logical reasoning or mathematical operations.
Reference: A reference answer to the question.
Response: The response generated by the model for the question.

Please analyze and evaluate according to the following Scoring Criteria:

5 points: The model's answer is consistent with the reference, and both the process and conclusion are correct.
4 points: The model's answer is consistent with the reference, but the process is simplistic or the perspective differs from the reference.
3 points: The conclusion is incorrect, but some parts of the reasoning process are correct; or the conclusion is correct, but key reasoning steps have obvious flaws or errors.
2 points: The conclusion is incorrect, and most of the reasoning process is invalid.
1 point: The conclusion is incorrect, and the reasoning process is chaotic, irrelevant, or incomplete.

Output Format: Please briefly describe your evaluation and fill in the final score in square brackets.
Example: The model's answer is consistent with the reference, but its steps are somewhat simplified. Score: [4]

Question: {question}
Reference: {reference}
Response: {pred}
  ***
  '''
    for i in range(10):
        messages = [
            {
                "role": "user",
                "content": prompt
            }
        ]
        print(messages)
        text = qwenmax(messages)["text"]
        try:
            score = int(re.findall(r'\[([1-5])\]', text)[0])
            return score, text
        except:
            score = 1
    return score, text


def qwenmax_eval_json(input_json, output_json):
    eval_data = []
    finished_len = 0
    correct_num = 0

    if os.path.exists(output_json):
        with open(output_json, "r") as f:
            finished = json.load(f)
        for item in finished:
            eval_data.append(item)
        finished_len = len(finished)
        
    with open("../json/reasoning.json", "r") as f:
        ref = json.load(f)
    with open(input_json, "r") as f:
        data = json.load(f)
    
    qwenmax = Qwen_Max(model_name="qwen-max-2025-01-25")
    for instance in data[finished_len:]:
        response = instance["Response"]
        index = int(instance["Qid"].split('-')[-1])
        question = ref[index]["Question"]
        reference = ref[index]["Answer"]
        ranges_with_ans = [(150, 350), (400, 500), (600, 900)]
        if any(lower <= index < upper for lower, upper in ranges_with_ans):
            correct, explain = qwenmax_eval_with_ans(question, response, reference, qwenmax)
        else:
            score, explain = qwenmax_eval_open_domain(question, response, reference, qwenmax)
            correct = (score > 3)
           
        eval_data.append({
            "Qid": instance["Qid"],
            "Question": question,
            "Reference": reference,
            "Response": response,
            "Correct": correct,
            "Explain": explain
        })
        with open(output_json, 'w+', encoding='utf-8') as f:
            json.dump(eval_data, f, ensure_ascii=False, indent=4)

    for instance in eval_data:
        correct_num += instance['Correct']
    print(f"S2T Accuracy: {correct_num/len(eval_data)*100}%")

if __name__ == "__main__": 
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_json", type=str)
    parser.add_argument("--output_json", type=str)
    args = parser.parse_args()

    qwenmax_eval_json(args.input_json, args.output_json)

